package com.uestcfir.mapper;

import com.uestcfir.pojo.entity.IotRoomStatus;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface IotRoomStatusMapper {
    @Insert("""
            INSERT INTO iot_room_status (
                room_code,
                room_id,
                device_id,
                latest_record_id,
                event_type,
                temperature,
                humidity,
                temperature_status,
                humidity_status,
                co2_ppm,
                light,
                light_raw,
                light_status,
                light_lux,
                smoke,
                smoke_raw,
                smoke_level,
                noise_db,
                distance_cm,
                person_near,
                presence,
                last_motion_time,
                people_count,
                motion_detected,
                face_detected,
                face_count,
                authorized,
                access_result,
                door_state,
                servo_angle,
                door_open,
                alarm,
                cooling,
                heating,
                humidifier,
                dehumidifier,
                projector,
                light_on,
                curtain_open,
                buzzer_on,
                auto_mode,
                sensor_status,
                error_message,
                payload_json,
                last_reported_at,
                create_time,
                update_time
            ) VALUES (
                #{roomCode},
                #{roomId},
                #{deviceId},
                #{latestRecordId},
                #{eventType},
                #{temperature},
                #{humidity},
                #{temperatureStatus},
                #{humidityStatus},
                #{co2Ppm},
                #{light},
                #{lightRaw},
                #{lightStatus},
                #{lightLux},
                #{smoke},
                #{smokeRaw},
                #{smokeLevel},
                #{noiseDb},
                #{distanceCm},
                #{personNear},
                #{presence},
                #{lastMotionTime},
                #{peopleCount},
                #{motionDetected},
                #{faceDetected},
                #{faceCount},
                #{authorized},
                #{accessResult},
                #{doorState},
                #{servoAngle},
                #{doorOpen},
                #{alarm},
                #{cooling},
                #{heating},
                #{humidifier},
                #{dehumidifier},
                #{projector},
                #{lightOn},
                #{curtainOpen},
                #{buzzerOn},
                #{autoMode},
                #{sensorStatus},
                #{errorMessage},
                #{payloadJson},
                #{lastReportedAt},
                #{createTime},
                #{updateTime}
            )
            ON DUPLICATE KEY UPDATE
                room_code = VALUES(room_code),
                device_id = VALUES(device_id),
                latest_record_id = VALUES(latest_record_id),
                event_type = VALUES(event_type),
                temperature = VALUES(temperature),
                humidity = VALUES(humidity),
                temperature_status = VALUES(temperature_status),
                humidity_status = VALUES(humidity_status),
                co2_ppm = VALUES(co2_ppm),
                light = VALUES(light),
                light_raw = VALUES(light_raw),
                light_status = VALUES(light_status),
                light_lux = VALUES(light_lux),
                smoke = VALUES(smoke),
                smoke_raw = VALUES(smoke_raw),
                smoke_level = VALUES(smoke_level),
                noise_db = VALUES(noise_db),
                distance_cm = VALUES(distance_cm),
                person_near = VALUES(person_near),
                presence = VALUES(presence),
                last_motion_time = VALUES(last_motion_time),
                people_count = VALUES(people_count),
                motion_detected = VALUES(motion_detected),
                face_detected = VALUES(face_detected),
                face_count = VALUES(face_count),
                authorized = VALUES(authorized),
                access_result = VALUES(access_result),
                door_state = VALUES(door_state),
                servo_angle = VALUES(servo_angle),
                door_open = VALUES(door_open),
                alarm = VALUES(alarm),
                cooling = VALUES(cooling),
                heating = VALUES(heating),
                humidifier = VALUES(humidifier),
                dehumidifier = VALUES(dehumidifier),
                projector = VALUES(projector),
                light_on = VALUES(light_on),
                curtain_open = VALUES(curtain_open),
                buzzer_on = VALUES(buzzer_on),
                auto_mode = VALUES(auto_mode),
                sensor_status = VALUES(sensor_status),
                error_message = VALUES(error_message),
                payload_json = VALUES(payload_json),
                last_reported_at = VALUES(last_reported_at),
                update_time = VALUES(update_time)
            """)
    int upsert(IotRoomStatus roomStatus);

    @Select("""
            SELECT *
            FROM iot_room_status
            WHERE room_id = #{roomId}
            """)
    IotRoomStatus findByRoomId(@Param("roomId") Integer roomId);
}
