CREATE TABLE IF NOT EXISTS iot_device (
    device_id VARCHAR(64) PRIMARY KEY,
    room_code VARCHAR(64) NULL,
    room_id INT NOT NULL,
    device_name VARCHAR(100) NULL,
    device_type VARCHAR(50) NOT NULL DEFAULT 'raspberrypi',
    protocol VARCHAR(32) NOT NULL DEFAULT 'websocket',
    online_status VARCHAR(16) NOT NULL DEFAULT 'online',
    last_seen_at DATETIME NOT NULL,
    last_reported_at DATETIME NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_iot_device_room (room_id),
    INDEX idx_iot_device_room_code (room_code),
    INDEX idx_iot_device_seen (last_seen_at)
);

CREATE TABLE IF NOT EXISTS iot_sensor_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    device_id VARCHAR(64) NOT NULL,
    room_code VARCHAR(64) NULL,
    room_id INT NOT NULL,
    event_type VARCHAR(32) NOT NULL DEFAULT 'telemetry',
    temperature DECIMAL(6, 2) NULL,
    humidity DECIMAL(6, 2) NULL,
    temperature_status VARCHAR(32) NULL,
    humidity_status VARCHAR(32) NULL,
    co2_ppm DECIMAL(10, 2) NULL,
    light INT NULL,
    light_raw INT NULL,
    light_status VARCHAR(32) NULL,
    light_lux DECIMAL(10, 2) NULL,
    smoke DECIMAL(10, 2) NULL,
    smoke_raw INT NULL,
    smoke_level VARCHAR(32) NULL,
    noise_db DECIMAL(6, 2) NULL,
    distance_cm DECIMAL(10, 2) NULL,
    person_near TINYINT(1) NULL,
    presence TINYINT(1) NULL,
    last_motion_time DATETIME NULL,
    people_count INT NULL,
    motion_detected TINYINT(1) NULL,
    face_detected TINYINT(1) NULL,
    face_count INT NULL,
    authorized TINYINT(1) NULL,
    access_result VARCHAR(32) NULL,
    door_state VARCHAR(16) NULL,
    servo_angle INT NULL,
    door_open TINYINT(1) NULL,
    alarm TINYINT(1) NULL,
    cooling TINYINT(1) NULL,
    heating TINYINT(1) NULL,
    humidifier TINYINT(1) NULL,
    dehumidifier TINYINT(1) NULL,
    light_on TINYINT(1) NULL,
    curtain_open TINYINT(1) NULL,
    buzzer_on TINYINT(1) NULL,
    sensor_status VARCHAR(32) NULL,
    error_message VARCHAR(255) NULL,
    payload_json TEXT NOT NULL,
    reported_at DATETIME NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_iot_room_time (room_id, reported_at),
    INDEX idx_iot_room_code_time (room_code, reported_at),
    INDEX idx_iot_device_time (device_id, reported_at)
);

CREATE TABLE IF NOT EXISTS iot_room_status (
    room_id INT PRIMARY KEY,
    room_code VARCHAR(64) NULL,
    device_id VARCHAR(64) NOT NULL,
    latest_record_id BIGINT NULL,
    event_type VARCHAR(32) NOT NULL DEFAULT 'telemetry',
    temperature DECIMAL(6, 2) NULL,
    humidity DECIMAL(6, 2) NULL,
    temperature_status VARCHAR(32) NULL,
    humidity_status VARCHAR(32) NULL,
    co2_ppm DECIMAL(10, 2) NULL,
    light INT NULL,
    light_raw INT NULL,
    light_status VARCHAR(32) NULL,
    light_lux DECIMAL(10, 2) NULL,
    smoke DECIMAL(10, 2) NULL,
    smoke_raw INT NULL,
    smoke_level VARCHAR(32) NULL,
    noise_db DECIMAL(6, 2) NULL,
    distance_cm DECIMAL(10, 2) NULL,
    person_near TINYINT(1) NULL,
    presence TINYINT(1) NULL,
    last_motion_time DATETIME NULL,
    people_count INT NULL,
    motion_detected TINYINT(1) NULL,
    face_detected TINYINT(1) NULL,
    face_count INT NULL,
    authorized TINYINT(1) NULL,
    access_result VARCHAR(32) NULL,
    door_state VARCHAR(16) NULL,
    servo_angle INT NULL,
    door_open TINYINT(1) NULL,
    alarm TINYINT(1) NULL,
    cooling TINYINT(1) NULL,
    heating TINYINT(1) NULL,
    humidifier TINYINT(1) NULL,
    dehumidifier TINYINT(1) NULL,
    light_on TINYINT(1) NULL,
    curtain_open TINYINT(1) NULL,
    buzzer_on TINYINT(1) NULL,
    sensor_status VARCHAR(32) NULL,
    error_message VARCHAR(255) NULL,
    payload_json TEXT NULL,
    last_reported_at DATETIME NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_iot_room_status_code (room_code),
    INDEX idx_iot_room_status_device (device_id),
    INDEX idx_iot_room_status_reported (last_reported_at)
);
